### ISSUE TITLE
Configuration-as-Code compatibility

### ISSUE THREAD

**Issue by cpoenisch** [jenkinsci/ecutest-plugin#20]
Add full support for the [Jenkins Configuration as Code Plugin](https://github.com/jenkinsci/configuration-as-code-plugin). This mainly includes the global configurations for ECU-TEST installations and TEST-GUIDE servers.

Example configurations:

**ECU-TEST**
```
tool:
  ecu-test:
    installations:
    - home: "C:\\Program Files\\ECU-TEST 7.2"
      name: "ECU-TEST 7.2"
```

**TEST-GUIDE**
```
unclassified:
  test-guide:
    installations:
      - config:
        settings:
          - atx-boolean-setting:
            name: "uploadToServer"
            value: true
          - atx-text-setting:
            name: "serverURL"
            value: "127.0.0.1"
          - ...
        customSettings:
          - atx-custom-boolean-setting:
            name: "customOption"
            checked: true
          - atx-custom-text-setting:
            name: "customLabel"
            value: "test"
          - ...
      name: "TEST-GUIDE"
      toolName: "ECU-TEST"
```

Tracking: https://github.com/jenkinsci/configuration-as-code-plugin/issues/809
